Multiple inputs one output - with and w/o numpy

In [2]:
weights = [0.1, 0.2, 0]
toes = [8.5, 9.5, 9.9, 9.0];
wlrec = [0.65, 0.8, 0.8, 0.9];
nfans = [1.2, 1.3, 0.5, 1.0];
input = [toes[0], wlrec[0], nfans[0]];

In [3]:
def dot_product(information, knowledge):
    assert(len(information) == len(knowledge));
    output = 0;
    for i in range(len(information)):
        output += information[i] * knowledge[i];
    return output;

pred = dot_product(input, weights);
print('w/o: ' + str(pred));

w/o: 0.9800000000000001


In [4]:
import numpy as np

pred = np.dot(input, weights);
print('np: ' + str(pred));

np: 0.9800000000000001


Multiple inputs & outputs - with and w/o numpy

In [5]:
            #toes %win #fans
weights = [ [0.1, 0.1, -0.3],#hurt? 
            [0.1, 0.2, 0.0], #win?
            [0.0, 1.3, 0.1] ]#sad?

def vector_matrix_mult(information, knowledge):
    output = [];
    for i in range(len(knowledge)):
        output.append(dot_product(information, knowledge[i]));
    return output;    
pred = vector_matrix_mult(input, weights);

print('w/o: ' + str(pred));

w/o: [0.555, 0.9800000000000001, 0.9650000000000001]


In [6]:
input = [toes[0], wlrec[0], nfans[0]];
                    #toes %win #fans
weights = np.array([ [0.1, 0.1, -0.3],#hurt? 
                     [0.1, 0.2, 0.0], #win?
                     [0.0, 1.3, 0.1] ]).T;#sad?

pred = np.dot(input, weights);
print('np: ', pred);

np:  [0.555 0.98  0.965]


Multiple inputs & outputs with hidden layer - w/o

In [7]:
                 #toes %win #fans
hidden_weights = [[0.1, 0.2, -0.1],#hidden[0]
                  [-0.1, 0.1, 0.9], #hidden[1]
                  [0.1, 0.4, 0.1] ];#hidden[2]

                   # hid[0] hid[1] hid[2]
weights_toplayer = [ [0.3, 1.1, -0.3],#hurt?
                     [0.1, 0.2, 0.0], #win?
                     [0.0, 1.3, 0.1] ]#sad?

weights = [hidden_weights, weights_toplayer];
def neural_network(input, weights):
    hidden_pred = vector_matrix_mult(input, weights[0]);
    print('Pred hidden: ' + str(hidden_pred));
    pred = vector_matrix_mult(hidden_pred, weights[1]);
    return pred;

pred = neural_network(input,weights);
print('Pred: ' + str(pred));


Pred hidden: [0.8600000000000001, 0.29499999999999993, 1.23]
Pred: [0.21350000000000002, 0.14500000000000002, 0.5065]


In [9]:
                           #toes %win #fans
hidden_weights = np.array([ [0.1, 0.2, -0.1],#hidden[0]
                            [-0.1, 0.1, 0.9], #hidden[1]
                            [0.1, 0.4, 0.1] ]).T;#hidden[2]

                            # hid[0] hid[1] hid[2]
weights_toplayer = np.array([ [0.3, 1.1, -0.3],#hurt?
                              [0.1, 0.2, 0.0],#win?
                              [0.0, 1.3, 0.1],#sad?
                              [0.3, .1, 1.4] ]).T;#don`t care, whatever.

weights = [hidden_weights, weights_toplayer];
def neural_network(input, weights):
    pred_hidden = np.dot(input, weights[0]);
    print('Pred hidden: ' + str(pred_hidden));
    pred = np.dot(pred_hidden, weights[1]);
    return pred;

pred = neural_network(input, weights);
print('Pred: ' + str(pred));

Pred hidden: [0.86  0.295 1.23 ]
Pred: [0.2135 0.145  0.5065 2.0095]


A prime on numpy - Break down the magic.

In [12]:
a = np.array([ 0, 1, 2, 3]);
b = np.array([ 4, 5, 6, 7]);
c = np.array([ [ 0, 1, 2, 3],
               [ 4, 5, 6, 7] ]);#matrix ♥

d = np.zeros((2, 4));
e = np.random.rand(2, 5);
f = np.zeros((1, 4));
g = np.zeros((4, 3));
i = np.zeros((3,5)).T;
print('#######Variables#######');
print('a: ' + str(a));
print('b: ' + str(b));
print('c: ' + str(c));
print('d: ' + str(d));
print('e: ' + str(e));
print('e: ' + str(f));
print('e: ' + str(g));

print('\n#####Elementwise anything########');

print(a * .1);
print(c * .2);
print(a * b);
print(a * b * .2);
print((a * c));
#print(a * e);
#ValueError: operands could not be broadcast
#together with shapes (4,) (2,5);

print('\n#########Dot Product########');
print('f.dot(g): ' + str(f.dot(g).shape));
print('e.dot(i): ' + str(e.dot(i).shape));

#######Variables#######
a: [0 1 2 3]
b: [4 5 6 7]
c: [[0 1 2 3]
 [4 5 6 7]]
d: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
e: [[0.07473464 0.30079775 0.43095647 0.04659235 0.96872454]
 [0.97901961 0.7193479  0.22345625 0.70696858 0.38762424]]
e: [[0. 0. 0. 0.]]
e: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

#####Elementwise anything########
[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]

#########Dot Product########
f.dot(g): (1, 3)
e.dot(i): (2, 3)
