In [22]:
import numpy as np

#Hyperparameters
np.random.seed(1);
hidden_size = 4;
alpha = .2;

#two datasets
#input
streetlights = np.array([ [1, 0, 1],
                          [0, 1, 1],
                          [0, 0, 1],
                          [1, 1, 1] ]);

#output 
walk_vs_stop = np.array([ [1, 0, 0, 0] ]).T

#two sets of weights now to connect our 3 layers
weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1;
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1;

print('Weights_0_1: ' + str(weights_0_1));
print('Weights_1_2: ' + str(weights_1_2));

Weights_0_1: [[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
Weights_1_2: [[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]


In [23]:
#this function sets all negative numbers to zero;
def relu(x):
    #it returns true or false, as well the number that 
    #represent these states i.e. 0 and 1;
    #value = (x > 0) - x; here, if it's true 1 - x otherwise 0 - x;  
    value = (x > 0) * x; 
    print(value);
    return value;

#defining layers
layer_0 = streetlights[0];
layer_1 = relu(np.dot(layer_0, weights_0_1));
layer_2 = layer_1.dot(weights_1_2);


[-0.          0.51828245 -0.         -0.        ]


Weighted sums are made into the nodes. For each node at layer_1 we perform a weighted sum. 
These weighted sums are then passed through  the 'relu' funtion, having all negative values converted to zero.
A last weighted sum is then performed into the final node at layer 2.

**IT'S TIME** - How can we learn the amount that each weight contributed to the error? Backpropagation in code.

In [87]:
import numpy as np

np.random.seed(1);

alpha = .2;
hidden_size = 4;

weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1;
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1;

def relu(x):
    return (x > 0) * x;

def relu2deriv(output):
    return output > 0;

for interaction in range(60):
    layer_2_error = 0;
    for index in range(len(streetlights)):
        layer_0 = streetlights[index:index+1];
        layer_1 = relu(layer_0.dot(weights_0_1));
        layer_2 = layer_1.dot(weights_1_2);
        
        mserror_layer_2 = (np.subtract(layer_2, walk_vs_stop[index:index+1])) ** 2;
        layer_2_error += mserror_layer_2;
        
        delta = np.subtract(layer_2, walk_vs_stop[index: index + 1]);
        weight_delta = 
        break;
    break;

[[0.36973299]]
[[-0.60805673]]


In [74]:
#random area for testing
for index in range(len(streetlights)):
        layer_0 = streetlights[index : index + 1];
        layer_1 = relu(layer_0.dot(weights_0_1));
        print(layer_1);
        



some_array = [0, 2, 4, 6];
print(type(some_array));
some_array = np.array(some_array);
print(type(some_array));

[[-0.          0.51828245 -0.         -0.        ]]
[[-0.         -0.         -0.          0.06156045]]
[[-0.          0.07763347 -0.          0.370439  ]]
[[-0. -0. -0. -0.]]
<class 'list'>
<class 'numpy.ndarray'>
