A neural network has a very simple interface. It accepts an input variable as information and a weight variable as knowledge and outputs a prediction.

EVERY NEURAL NETWORK YOU'LL EVER SEE WORKS THIS WAY.

Another way to think about neural network's wight value is as a measure of sensitivity between the input and the output prediction.

WEIGHT IS A VOLUME KNOB

Paradigm[0] - Predict.
See next chapter for Paradigm[1] - Compare and [2] - Learn

Multiple inputs one output - with and w/o numpy

In [5]:
weights = [0.1, 0.2, 0]
toes = [8.5, 9.5, 9.9, 9.0];
wlrec = [0.65, 0.8, 0.8, 0.9];
nfans = [1.2, 1.3, 0.5, 1.0];
input = [toes[0], wlrec[0], nfans[0]];

In [6]:
def dot_product(information, knowledge):
    assert(len(information) == len(knowledge));
    output = 0;
    for i in range(len(information)):
        output += information[i] * knowledge[i];
    return output;

pred = dot_product(input, weights);
print('w/o: ' + str(pred));

w/o: 0.9800000000000001


In [7]:
import numpy as np

pred = np.dot(input, weights);
print('np: ' + str(pred));

np: 0.9800000000000001


Multiple inputs & outputs - with and w/o numpy

Think of it as each output node(prediction) takes its own weighted sum of the input.

In [8]:
            #toes %win #fans
weights = [ [0.1, 0.1, -0.3],#hurt? 
            [0.1, 0.2, 0.0], #win?
            [0.0, 1.3, 0.1] ]#sad?

def vector_matrix_mult(information, knowledge):
    output = [];
    for i in range(len(knowledge)):
        output.append(dot_product(information, knowledge[i]));
    return output;    
pred = vector_matrix_mult(input, weights);

print('w/o: ' + str(pred));

w/o: [0.555, 0.9800000000000001, 0.9650000000000001]


In [9]:
input = [toes[0], wlrec[0], nfans[0]];
                    #toes %win #fans
weights = np.array([ [0.1, 0.1, -0.3],#hurt? 
                     [0.1, 0.2, 0.0], #win?
                     [0.0, 1.3, 0.1] ]).T;#sad?

pred = np.dot(input, weights);
print('np: ', pred);

np:  [0.555 0.98  0.965]


> We use the knowledge to interpret the information

Multiple inputs & outputs with hidden layer - w/o

In [12]:
                 #toes %win #fans
hidden_weights = [[0.1, 0.2, -0.1],#hidden[0]
                  [-0.1, 0.1, 0.9], #hidden[1]
                  [0.1, 0.4, 0.1] ];#hidden[2]

                   # hid[0] hid[1] hid[2]
weights_to_player = [ [0.3, 1.1, -0.3],#hurt?
                     [0.1, 0.2, 0.0], #win?
                     [0.0, 1.3, 0.1],#sad?
                     [0.3, .1, 1.4] ] #don`t care, whatever.

weights = [hidden_weights, weights_to_player];
def neural_network(input, weights):
    hidden_pred = vector_matrix_mult(input, weights[0]);
    print('Pred hidden: ' + str(hidden_pred));
    pred = vector_matrix_mult(hidden_pred, weights[1]);
    return pred;

pred = neural_network(input,weights);
print('Pred: ' + str(pred));


Pred hidden: [0.8600000000000001, 0.29499999999999993, 1.23]
Pred: [0.21350000000000002, 0.14500000000000002, 0.5065, 2.0095]


In [4]:
                           #toes %win #fans
hidden_weights = np.array([ [0.1, 0.2, -0.1],#hidden[0]
                            [-0.1, 0.1, 0.9], #hidden[1]
                            [0.1, 0.4, 0.1] ]).T;#hidden[2]

                            # hid[0] hid[1] hid[2]
weights_toplayer = np.array([ [0.3, 1.1, -0.3],#hurt?
                              [0.1, 0.2, 0.0],#win?
                              [0.0, 1.3, 0.1],#sad?
                              [0.3, .1, 1.4] ]).T;#don`t care, whatever.

weights = [hidden_weights, weights_toplayer];
def neural_network(input, weights):
    pred_hidden = np.dot(input, weights[0]);
    print('Pred hidden: ' + str(pred_hidden));
    pred = np.dot(pred_hidden, weights[1]);
    return pred;

pred = neural_network(input, weights);
print('Pred: ' + str(pred));

Pred hidden: [0.86  0.295 1.23 ]
Pred: [0.2135 0.145  0.5065 2.0095]


**Elementwise operation**: 

Vectors of equal length that you pair up in order to make mathmatical operations.

**A prime on numpy** - Break down the magic.

In [29]:
a = np.array([ 0, 1, 2, 3]);
b = np.array([ 4, 5, 6, 7]);
c = np.array([ [ 0, 1, 2, 3],
               [ 4, 5, 6, 7] ]);#matrix ♥

d = np.array([[1], [2]]);
e = np.random.randint(6, size=(2, 5));
f = np.zeros((1, 4));
g = np.zeros((4, 3));
i = np.random.randint(4, size=(3,5));

print('#######Variables#######');
print('a: ' + str(a));
print('b: ' + str(b));
print('c: ' + str(c));
print('d: ' + str(d));
print('e: ' + str(e));
print('f: ' + str(f));
print('g: ' + str(g));
print('i: ' + str(i));

print('\n#####Elementwise anything########');
print(a * .1);
print(c * .2);
print(a * b);
print(a * b * .2);
print((a * c));
print(c * d);

#ValueError: operands could not be broadcast
#together with shapes (4,) (2,5);
#print(a * e);

print('\n#########Dot Product########');
print('f.dot(g): ' + str(f.dot(g).shape));
print('e.dot(i): ' + str(e.dot(i.T)));

#######Variables#######
a: [0 1 2 3]
b: [4 5 6 7]
c: [[0 1 2 3]
 [4 5 6 7]]
d: [[1]
 [2]]
e: [[2 2 4 5 2]
 [3 4 4 3 5]]
f: [[0. 0. 0. 0.]]
g: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
i: [[2 0 2 3 3]
 [2 2 0 1 3]
 [1 1 3 0 3]]

#####Elementwise anything########
[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]
[[ 0  1  2  3]
 [ 8 10 12 14]]

#########Dot Product########
f.dot(g): (1, 3)
e.dot(i): [[33 19 22]
 [38 32 34]]


The rule for elementwise operation is that:
>Either the two variables must have the same number of columns OR
>One the variables must have only one column

All we've done so is a form of what's called **forward propagation**: `You're propagating activations forward through the network.`

>**Activations** are all numbers that are not weights and are unique to the prediction.