Matrix A * 10 == Matrix B - These matrices are scalar multiple of each other;

Learn one streetlight:

In [79]:
import numpy as np;

alpha = .1
iterations = 40
#The streetlight pattern;
streetlights = np.array([ [1, 0, 1],
                         [0, 1, 1], 
                         [0, 0, 1],
                         [1, 1, 1],
                         [0, 1, 1],
                         [1, 0, 1] ]);

streetlight = streetlights[0]
#1 means walk, 0 means stop;
# lossless representation: 
# >can perfectly convert back and forth between 
# >our stop/walk notes and our matrix;
goal_pred = np.array([ 0, 1, 0, 1, 1, 0 ]);

Stochastic gradient descent - Update weights for each training example

In [89]:
np.random.seed(1)
weight = np.random.rand(3)
print(weight)

def neural_network(input, weight):
    for iteration in range(iterations):
        error = 0
        preds = []
        for index, observation in enumerate(input):
            pred = observation.dot(weight)
            preds.append(pred)
            delta = pred - goal_pred[index]
            error += delta ** 2
            weight_delta = delta * observation
            weight -= weight_delta * alpha
        print('Error: ' + str(error))
        print('Pred: ' + str(preds) + '\n-----------------------------')
    print('Weight: ' + str(weight))
            
neural_network(streetlights, weight)

[4.17022005e-01 7.20324493e-01 1.14374817e-04]
Error: 0.507470215713197
Pred: [0.4171363795199189, 0.6787252303075111, -0.009471786165398115, 1.1192357296131308, 0.7200802169399225, 0.3709285915851054]
-----------------------------
Error: 0.31560515640555536
Pred: [0.29674287326808435, 0.709297027066619, -0.030153051396144506, 1.0670705740968598, 0.7570388119735377, 0.2803619050306943]
-----------------------------
Error: 0.2020506734994488
Pred: [0.22428952402455543, 0.7551659066733052, -0.03553041843642529, 1.0471312141710258, 0.7982595243480816, 0.21821587512694304]
-----------------------------
Error: 0.13022294889293376
Pred: [0.17457270010155443, 0.7993287619556154, -0.03572818416310479, 1.0384892960295895, 0.835337968774885, 0.17206644621858605]
-----------------------------
Error: 0.0841700986788962
Pred: [0.13765315697486885, 0.8372984147005624, -0.034239894016643485, 1.0338952992885966, 0.8664836613043949, 0.1363892475233444]
-----------------------------
Error: 0.05455017392

Full gradient descent - Update weights for the entire dataset

In [90]:
np.random.seed(1)
weight = np.random.rand(3)
print(weight)

def neural_network(input, weight):
    for i in range(iterations):  
        pred = input.dot(weight);
        msquared_error = np.sum((pred - goal_pred) ** 2) / len(input);
        delta = pred - goal_pred;
        weight_delta = delta.dot(input);
        weight -= weight_delta * alpha;
        print('Error: ' + str(msquared_error)); 
        print('Pred: ' + str(pred) + '\n-----------------------------')
    print('Weight: ' + str(weight))

    
neural_network(streetlights, weight);
# random_v3c = np.random.rand(6);
# print('rand: ' + str(random_v3c) + ' goal: ' + str(goal_pred.shape));
# sub = random_v3c - goal_pred;
# print(sub);

[4.17022005e-01 7.20324493e-01 1.14374817e-04]
Error: 0.08720164594585363
Pred: [4.17136380e-01 7.20438868e-01 1.14374817e-04 1.13746087e+00
 7.20438868e-01 4.17136380e-01]
-----------------------------
Error: 0.05233963816862639
Pred: [ 0.27869044  0.72133243 -0.0411582   1.04118107  0.72133243  0.27869044]
-----------------------------
Error: 0.03361027010807473
Pred: [ 0.21882738  0.77294098 -0.04116506  1.03293342  0.77294098  0.21882738]
-----------------------------
Error: 0.021622416242555387
Pred: [ 0.17423806  0.81752893 -0.03869557  1.03046256  0.81752893  0.17423806]
-----------------------------
Error: 0.01393636211776795
Pred: [ 0.13881409  0.85344679 -0.03622567  1.02848655  0.85344679  0.13881409]
-----------------------------
Error: 0.00900512295505589
Pred: [ 0.11052435  0.88223051 -0.03390393  1.0266588   0.88223051  0.11052435]
-----------------------------
Error: 0.00583847489035693
Pred: [ 0.08792714  0.90529207 -0.03173039  1.02494961  0.90529207  0.08792714]
----

What if our input node does not have any correlation with our output node? What does it do to our linear network? let's find out.

In [128]:
alpha = .5
iterations = 300
#The streetlight pattern;
streetlights = np.array([ [1, 0, 1],
                          [0, 1, 1],
                          [0, 0, 1],
                          [1, 1, 1] ]);

#1 means walk, 0 means stop;
# lossless representation: 
# >can perfectly convert back and forth between 
# >our stop/walk notes and our matrix;
goal_pred = np.array([ 1, 1, 0, 0 ]);

In [117]:
np.random.seed(1)
weight = np.random.rand(3)
print(weight)

def neural_network(input, weight):
    for iteration in range(iterations):
        error = 0
        preds = []
        for index, observation in enumerate(input):
            pred = observation.dot(weight)
            preds.append(pred)
            delta = pred - goal_pred[index]
            error += delta ** 2
            weight_delta = delta * observation
            weight -= weight_delta * alpha
        if(iteration > 295):
                print('Error: ' + str(error))
                print('Pred: ' + str(preds) + '\n-----------------------------')
            
    print('Weight: ' + str(weight))
            
neural_network(streetlights, weight)

[4.17022005e-01 7.20324493e-01 1.14374817e-04]
Error: 4.0
Pred: [0.0, 0.0, 1.0, 1.0]
-----------------------------
Error: 4.0
Pred: [0.0, 0.0, 1.0, 1.0]
-----------------------------
Error: 4.0
Pred: [0.0, 0.0, 1.0, 1.0]
-----------------------------
Error: 4.0
Pred: [0.0, 0.0, 1.0, 1.0]
-----------------------------
Weight: [ 0.  -0.5  0. ]


Well it predicted the exact opposite, how nice!

Let's add nonlinearity and hidden layers to the mix to see if we can correlate.

Weighted sums are performed in the nodes.

In [148]:
np.random.seed(1)

alpha = .2
hidden_size = 4
iterations = 60

goal_pred = np.array([[ 1, 1, 0, 0 ]]).T;

weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1

weights = {
            'weights_0_1': weights_0_1,
            'weights_1_2': weights_1_2
          }

def relu(x):
    return (x > 0) * x

def relu2deriv(output):
    return output > 0

def neural_net(input: np.ndarray, weights: dict):
    
    for iteration in range(iterations):
        error = 0
        preds = []
        
        for index, obs in enumerate(input):
            layer_0 = input[index:index+1]
            layer_1 = relu(layer_0.dot(weights['weights_0_1']))
            layer_2 = layer_1.dot(weights['weights_1_2'])
            
            preds.append(layer_2)
            layer_2_delta = layer_2 - goal_pred[index:index+1]
            layer_1_delta = layer_2_delta.dot(weights['weights_1_2'].T) * relu2deriv(layer_1)
            error += (layer_2_delta ** 2)
            
            weights_1_2_delta = layer_1.T.dot(layer_2_delta)
            weights_0_1_delta = layer_0.T.dot(layer_1_delta)
            
            weights['weights_1_2'] -= (weights_1_2_delta * alpha)
            weights['weights_0_1'] -= (weights_0_1_delta * alpha)            
            
        print('Error: ' + str(error))
        print('Pred: ' + str(preds) + '\n-----------------------------')
    
    print('Weight: ' + str(weights))       
    
neural_net(streetlights, weights)    

Error: [[1.41420584]]
Pred: [array([[0.39194327]]), array([[0.02098811]]), array([[0.29327219]]), array([[0.]])]
-----------------------------
Error: [[1.21271615]]
Pred: [array([[0.53634943]]), array([[0.06741661]]), array([[0.35781632]]), array([[0.]])]
-----------------------------
Error: [[1.05656376]]
Pred: [array([[0.67382026]]), array([[0.10937117]]), array([[0.39543008]]), array([[0.02420473]])]
-----------------------------
Error: [[0.94916648]]
Pred: [array([[0.76081998]]), array([[0.15331219]]), array([[0.41249809]]), array([[0.07017463]])]
-----------------------------
Error: [[0.86196212]]
Pred: [array([[0.81109594]]), array([[0.20020963]]), array([[0.41573064]]), array([[0.11739149]])]
-----------------------------
Error: [[0.78450684]]
Pred: [array([[0.83854849]]), array([[0.24915731]]), array([[0.40940342]]), array([[0.16451243]])]
-----------------------------
Error: [[0.71464898]]
Pred: [array([[0.85254688]]), array([[0.29776432]]), array([[0.39521967]]), array([[0.20

In [ ]:
np.random.seed(1);
hidden_size = 5
alpha = .0005

def relu(x):
   return (x > 0) * x

def relu2deriv(x):
   return x > 0

goal_pred = np.reshape(goal_pred, (6, 1))
synapse_0_1 = np.random.randint(0, 12, (3, hidden_size))
synapse_1_2 = np.random.rand(hidden_size, 1)

for i in range(3000):
    layer_1 = relu(streetlights.dot(synapse_0_1))
    layer_2 = layer_1.dot(synapse_1_2)
    layer_2_delta = layer_2 - goal_pred
    msquared_error = layer_2_delta ** 2
    layer_1_delta = layer_2_delta.dot(synapse_1_2.T) * relu2deriv(layer_1)
    synapse_1_2_delta = layer_1.T.dot(layer_2_delta)  
    synapse_0_1_delta = streetlights.T.dot(layer_1_delta)
    synapse_1_2 = synapse_1_2 - synapse_1_2_delta * alpha
    synapse_0_1 = synapse_0_1 - synapse_0_1_delta * alpha
    if (i % 10 == 0):
        print('\nPred: ' + str(layer_2.T) + ' Error: ' + str(msquared_error.T) + ' Goal: ' + str(goal_pred.T))
    #print('\nLayer_1: ' + str(layer_1) + ' Synapse_1_2: ' + str(synapse_1_2))
    

Neural networks can learn correlation:
> In the previous example the network identified correlation between the middle input and the output;
The Correlation is located whatever the weights were set to higher numbers - Signal;
Inversely, _randomness_ with respect to the output was found at the far left and far right weights(where the weight values are near to 0). - Noise;


Cross comunication between neurons occurs by sharing the same error measurement.
>It makes it clear that our weight update is nothing more than taking this shared error measument
and multiplying it by each respective input.

Full-batch Gradient Descent: 
>Updating weights one dataset at a time;

Batch Gradient Descent:
>Updating weights after 'n' observations;

**Backpropagation: Long distance error attribuition**

The "weighted average error"

Bottom line: Trask use the fact that we want to know how to calculate delta to our lower layer(layer_0 to layer_1), in a way that these values can  help our upper layer(layer_2) to predict accurately.

"moving delta signal around" - weighted average delta.